import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'

import ProviderCart from '@/providers/cart-provider'
import { CheckoutHeader } from '@/components/ui/checkout-header'
import ProviderAuth from '@/providers/auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ProviderAuth>
          <ProviderCart>
            {children}
          </ProviderCart>
        </ProviderAuth>
      </body>
    </html>
  )
}
