import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'

import Header from '@/components/ui/header'
import { CartProvider } from '@/contexts/cart-context'
import { Navigation } from '@/interfaces/navigation-types'
import { AuthProvider } from '@/contexts/auth-context'

import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  const navigation: Navigation[] = [
    { name: "Categorias", href: "/categories" },
    { name: "Parceiros", href: "/partners" },
    { name: "Destaques da semana", href: "/highlight" },
    { name: "Promoção", href: "/promotion" },
  ]

  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <Header navigation={navigation} />
            <ToastContainer autoClose={2000} />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
