import { ReactNode } from 'react'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function LoginLayout({
    children
}: Readonly<{
    children: ReactNode
}>) {

    return (
        <html lang='en'>
            <body className={inter.className}>
                {/* aqui vai ter o auth provider */}
                <ToastContainer autoClose={2000} />
                {children}
            </body>
        </html>
    )
}